# numpy

In [ ]:
s = np.array([(2,12), (3,11), (3,8), (5,4), (7,5), (7,3), (10,8), (13,8)])

# Tuple

In [ ]:
[(),()]

# KNN

In [5]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier


# Example data:
# The tuple (x_1, x_2, x_3, y) means that the point (x_1, x_2, x_3)^T is in class y
exampledata = [
	(   -4,  -2.1,    -1,  -1 ),
	( -3.6,  -1.4,   0.2,   1 ),
	(    1,  -0.2,  -0.3,   1 ),
	(  0.3,  -0.5,  -0.5,   1 ),
	(   -2,  -3.5,    -1,  -1 ),
	( -4.2,    -4,   0.2,   1 ),
	( -1.3,  -0.1,    -3,   1 ),
	( -0.7,   0.9,  -0.7,   1 ),
	(    1,     2,   1.4,   1 ),
	(  2.6,  -1.5,   0.2,   1 ),
	(    2,   4.3,  -0.7,  -1 ),
	(  0.6,   0.4,   0.2,  -1 ),
	(  2.9,  -1.7,   3.6,  -1 ),
	(  3.6,   0.4,  -2.5,  -1 ),
	(  1.2,     4,   1.2,  -1 ),
	(   -1,   0.5,   0.5,  -1 ),
	(    3,   2.7,   2.3,  -1 ),
	(    4,    -3,   2.2,  -1 ),
	(  0.1,   0.1,   3.5,  -1 ),
	(  2.8,   1.2,   2.4,  -1 )
]

# Data to classify
# The tuple (x_1, x_2, x_3) denotes the vector (x_1, x_2, x_3)^T
querypoints = [
	(  1,   -2,    0 ),
	(  4, -0.5,    2 ),
	(  1,  1.5, -2.5 ),
	( -2,   -1,   -2 ),
	( -4,   -1,   -1 )
]

# get data from exampledata
X = np.array([x[:3] for x in exampledata]) 

# get labels from exampledata
y = np.array([x[3] for x in exampledata])


# predict labels for querypoints using the k-nearest neighbor algorithm using manhattan distance
querypoints = np.array(querypoints)
knn = KNeighborsClassifier(n_neighbors=2, p=1)
knn.fit(X, y)
print(knn.predict(querypoints))

knn = KNeighborsClassifier(n_neighbors=3, p=1)
knn.fit(X, y)
print(knn.predict(querypoints))

# predict labels for querypoints using the k-nearest neighbor algorithm
querypoints = np.array(querypoints)
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X, y)
print(knn.predict(querypoints))


knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)
print(knn.predict(querypoints))

[ 1 -1 -1 -1 -1]
[ 1 -1  1 -1  1]
[ 1 -1  1 -1 -1]
[ 1 -1  1  1 -1]


In [1]:
# Example data:
# The tuple (x_1, x_2, x_3, y) means that the point (x_1, x_2, x_3)^T is in class y
import math


exampledata = [
	(   -4,  -2.1,    -1,  -1 ),
	( -3.6,  -1.4,   0.2,   1 ),
	(    1,  -0.2,  -0.3,   1 ),
	(  0.3,  -0.5,  -0.5,   1 ),
	(   -2,  -3.5,    -1,  -1 ),
	( -4.2,    -4,   0.2,   1 ),
	( -1.3,  -0.1,    -3,   1 ),
	( -0.7,   0.9,  -0.7,   1 ),
	(    1,     2,   1.4,   1 ),
	(  2.6,  -1.5,   0.2,   1 ),
	(    2,   4.3,  -0.7,  -1 ),
	(  0.6,   0.4,   0.2,  -1 ),
	(  2.9,  -1.7,   3.6,  -1 ),
	(  3.6,   0.4,  -2.5,  -1 ),
	(  1.2,     4,   1.2,  -1 ),
	(   -1,   0.5,   0.5,  -1 ),
	(    3,   2.7,   2.3,  -1 ),
	(    4,    -3,   2.2,  -1 ),
	(  0.1,   0.1,   3.5,  -1 ),
	(  2.8,   1.2,   2.4,  -1 )
]

# Data to classify
# The tuple (x_1, x_2, x_3) denotes the vector (x_1, x_2, x_3)^T
querypoints = [
	(  1,   -2,    0 ),
	(  4, -0.5,    2 ),
	(  1,  1.5, -2.5 ),
	( -2,   -1,   -2 ),
	( -4,   -1,   -1 )
]

# classify the query points using k-nearest neighbour with exampledata as training data
# and k = 2 with manhattan distance
def manhattan(q, e):
    return (abs(e[0]-q[0])+abs(e[1]-q[1])+abs(e[2]-q[2]))

def euclidean(q, e):
	return math.sqrt((e[0]-q[0])**2+(e[1]-q[1])**2+(e[2]-q[2])**2)

k = 2
# k = 3

for q in querypoints:
    # calculate the distances to all points in exampledata
	dis = []
	for e in exampledata:
		dis.append(manhattan(q, e))

	# sort the distances
	dis.sort()
	print(dis)


	# get the top k elements
	top = dis[:k]

	# count the labels of the top k elements
	count = 0
	for t in top:
		for e in exampledata:
			if abs(manhattan(q, e) - t) < 0.0001:
				print(e)
				count += e[3]
				break

	# check the sign of the count
	if count  ==  0:
		print("0")
	elif count  >  0:
		print("1")
	else:
		print("-1")


[2.1, 2.3000000000000003, 2.7, 3.0, 5.0, 5.3, 5.3999999999999995, 5.4, 5.5, 5.800000000000001, 6.1, 6.2, 6.5, 7.199999999999999, 7.4, 7.4, 7.4, 7.5, 8.0, 9.0]
(1, -0.2, -0.3, 1)
(2.6, -1.5, 0.2, 1)
1
[2.7, 3.3000000000000003, 3.9, 4.2, 4.5, 5.6, 5.8, 6.0, 6.1, 6.1, 6.2, 7.5, 8.1, 8.8, 9.5, 10.3, 10.7, 12.0, 12.6, 13.5]
(4, -3, 2.2, -1)
(2.8, 1.2, 2.4, -1)
-1
[3.7, 3.9000000000000004, 4.1, 4.2, 4.4, 4.4, 4.7, 5.6, 6.0, 6.4, 7.0, 7.3, 8.0, 8.3, 9.5, 10.1, 10.2, 11.2, 12.2, 13.399999999999999]
(3.6, 0.4, -2.5, -1)
(1, -0.2, -0.3, 1)
0
[2.6, 3.5, 4.1, 4.2, 4.3, 4.5, 5.0, 5.5, 6.2, 7.3, 7.4, 7.5, 8.7, 9.4, 10.600000000000001, 11.2, 11.399999999999999, 11.4, 12.2, 13.0]
(-1.3, -0.1, -3, 1)
(-2, -3.5, -1, -1)
0
[1.1, 1.9999999999999998, 4.4, 4.5, 5.3, 5.499999999999999, 5.6, 6.0, 6.5, 7.2, 8.299999999999999, 9.7, 10.4, 10.5, 11.600000000000001, 12.2, 12.399999999999999, 12.4, 13.2, 14.0]
(-4, -2.1, -1, -1)
(-3.6, -1.4, 0.2, 1)
0


# Kmeans

In [2]:
from sklearn.cluster import KMeans
import numpy as np

# 准备数据
s = np.array([(2,12), (3,11), (3,8), (5,4), (7,5), (7,3), (10,8), (13,8)])

# 定义初始中心点
init_centers = np.array([(2,12), (3,11), (3,8)])
# init_centers = np.array([(2,10), (6,4), (12,8)])

# 初始化KMeans模型
kmeans = KMeans(n_clusters=3, init=init_centers)

# 训练模型
kmeans.fit(s)

# 输出结果
print(kmeans.labels_)


[0 0 1 2 2 2 2 2]


/Users/hanbin/Library/Python/3.9/lib/python/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/Users/hanbin/Library/Python/3.9/lib/python/site-packages/sklearn/cluster/_kmeans.py:1362: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=10.
  super()._check_params_vs_input(X, default_n_init=10)
